// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaR9Kd3htMVeUUCuhSSTjmHGgAT2yCEto',
    appId: '1:994510824234:web:876777b63845184d75b453',
    messagingSenderId: '994510824234',
    projectId: 'ozapp-as1703',
    authDomain: 'ozapp-as1703.firebaseapp.com',
    storageBucket: 'ozapp-as1703.appspot.com',
  );

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyCZth2RlkEGi9BPmjJFBCGtEaw0bJGF_XA',
  //   appId: '1:994510824234:android:84b0cc20da51c48875b453',
  //   messagingSenderId: '994510824234',
  //   projectId: 'ozapp-as1703',
  //   storageBucket: 'ozapp-as1703.appspot.com',
  // );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHBz-SgnXasSjML1eA6LP9gv54sKrpMMs',
    appId: '1:1060579352484:android:596e018259181727042b31',
    messagingSenderId: '1060579352484',
    projectId: 'ozapp-alter',
    storageBucket: 'ozapp-alter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQX7GWijUxe6XPxHA_rvDQxc8zfcYfaLM',
    appId: '1:994510824234:ios:d052e1a9a2357ec475b453',
    messagingSenderId: '994510824234',
    projectId: 'ozapp-as1703',
    storageBucket: 'ozapp-as1703.appspot.com',
    iosBundleId: 'com.AScode.oz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQX7GWijUxe6XPxHA_rvDQxc8zfcYfaLM',
    appId: '1:994510824234:ios:d052e1a9a2357ec475b453',
    messagingSenderId: '994510824234',
    projectId: 'ozapp-as1703',
    storageBucket: 'ozapp-as1703.appspot.com',
    iosBundleId: 'com.AScode.oz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaR9Kd3htMVeUUCuhSSTjmHGgAT2yCEto',
    appId: '1:994510824234:web:606762a09639e7c175b453',
    messagingSenderId: '994510824234',
    projectId: 'ozapp-as1703',
    authDomain: 'ozapp-as1703.firebaseapp.com',
    storageBucket: 'ozapp-as1703.appspot.com',
  );
}
